"""Public dataclasses and enums for kenkui library state.

The package is split by domain, while this module preserves the historical
``kenkui.models`` import path for applications and serialized cache loaders.
"""

from .api import (
    AuditionRequest,
    BookAnalyzeRequest,
    BookParseRequest,
    BookParseResponse,
    BookScanRequest,
    CastEntry,
    CastResponse,
    ChapterFilterRequest,
    ChapterFilterResponse,
    ChapterSummaryModel,
    CharacterInfoModel,
    ConfigResponse,
    CreateEmptySeriesRequest,
    CreateSeriesFromCandidateRequest,
    DownloadRequest,
    FetchRequest,
    HealthResponse,
    HFAuthResponse,
    HFTokenRequest,
    JobCreateRequest,
    JobResponse,
    MultivoiceStatusResponse,
    NarratorRecommendationRequest,
    NarratorRecommendationResponse,
    OkResponse,
    ProviderCredentialListResponse,
    ProviderCredentialStatus,
    ProviderCredentialUpdateRequest,
    QueueResponse,
    RosterCandidateListResponse,
    RosterCandidateModel,
    SeriesCharacterModel,
    SeriesListResponse,
    SeriesMatchRequest,
    SeriesMatchResponse,
    SeriesModel,
    SimpleCastRequest,
    SimpleCastResponse,
    StatusResponse,
    SuggestCastRequest,
    SuggestCastResponse,
    TaskResponse,
    VoiceListResponse,
    VoicePoolResponse,
    VoiceResponse,
)
from .audio import AudioResult, ProcessingConfig
from .book import BookInfo, ChapterSelection, CharacterInfo, CharacterRecord
from .common import (
    AttributionExecutionMode,
    AttributionTool,
    ChapterPreset,
    CostStatus,
    ExtractionTool,
    JobStatus,
    NarrationMode,
    NlpExecutionMode,
    TTSExecutionMode,
    _migrate_speaker_voices_keys,
    _normalize_bitrate,
)
from .config import AppConfig, PostProcessingConfig
from .job import JobConfig
from .nlp import Chapter, FastScanResult, NLPResult, Segment
from .queue import QueueItem

__all__ = [
    "AppConfig",
    "AttributionExecutionMode",
    "AttributionTool",
    "AuditionRequest",
    "AudioResult",
    "BookAnalyzeRequest",
    "BookInfo",
    "BookParseRequest",
    "BookParseResponse",
    "BookScanRequest",
    "CastEntry",
    "CastResponse",
    "Chapter",
    "ChapterFilterRequest",
    "ChapterFilterResponse",
    "ChapterPreset",
    "ChapterSelection",
    "ChapterSummaryModel",
    "CharacterInfo",
    "CharacterInfoModel",
    "CharacterRecord",
    "ConfigResponse",
    "CostStatus",
    "CreateEmptySeriesRequest",
    "CreateSeriesFromCandidateRequest",
    "DownloadRequest",
    "ExtractionTool",
    "FetchRequest",
    "FastScanResult",
    "HFAuthResponse",
    "HFTokenRequest",
    "HealthResponse",
    "JobConfig",
    "JobCreateRequest",
    "JobResponse",
    "JobStatus",
    "MultivoiceStatusResponse",
    "NarrationMode",
    "NarratorRecommendationRequest",
    "NarratorRecommendationResponse",
    "NLPResult",
    "NlpExecutionMode",
    "OkResponse",
    "PostProcessingConfig",
    "ProcessingConfig",
    "ProviderCredentialListResponse",
    "ProviderCredentialStatus",
    "ProviderCredentialUpdateRequest",
    "QueueItem",
    "QueueResponse",
    "RosterCandidateListResponse",
    "RosterCandidateModel",
    "Segment",
    "SeriesCharacterModel",
    "SeriesListResponse",
    "SeriesMatchRequest",
    "SeriesMatchResponse",
    "SeriesModel",
    "SimpleCastRequest",
    "SimpleCastResponse",
    "StatusResponse",
    "SuggestCastRequest",
    "SuggestCastResponse",
    "TaskResponse",
    "TTSExecutionMode",
    "VoiceListResponse",
    "VoicePoolResponse",
    "VoiceResponse",
    "_migrate_speaker_voices_keys",
    "_normalize_bitrate",
]
